// const ALL_OR_NOTHING = 'ALL_OR_NOTHING';
// const OVERGENERALIZATION = 'OVERGENERALIZATION';
// const MENTAL_FILTER = 'MENTAL_FILTER';
// const DISQUALIFY_THE_POSITIVE = 'DISQUALIFY_THE_POSITIVE';
// const MIND_READING = 'MIND_READING';
// const FORTUNE_TELLING = 'FORTUNE_TELLING';
// const MAGNIFICATION = 'MAGNIFICATION';
// const EMOTIONAL_REASONING = 'EMOTIONAL_REASONING';
// const SHOULD_STATEMENTS = 'SHOULD_STATEMENTS';
// const MISLABELLING = 'MISLABELLING';

console.log("from main.js");
